[project]
name = "artikel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pip>=24.3.1",
    "pynput>=1.7.7",
    "pyperclip>=1.9.0",
    "spacy>=3.8.3",
]


#  uv run -- spacy download de_dep_news_trf