version: '3'

tasks:
  pip:install:
    desc: "Install dependencies using pip"
    cmds:
      - python -m venv .env
      - .env/Scripts/activate
      - pip install -U pip setuptools wheel
      - pip install -U spacy pywin32 keyboard
      - python -m spacy download en_core_web_sm
      - python -m spacy download de_core_news_sm