version: '3'

tasks:
  uv:install:
    desc: "Install dependencies"
    cmds:
      - uv sync
      - uv run -- spacy download de_dep_news_trf # german language model
  uv:run:
    desc: "Run the program"
    cmds:
      - uv run artikel_finder.py
